/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux adam-virtual-machine 6.8.0-49-generic x86_64"
#define YALS_COMPILED "Po  9. december 2024, 17:43:34 CET"
#define YALS_RELEASED "Po  9. december 2024, 17:43:34 CET"
#define YALS_VERSION "1.0.1"
#define YALS_ID "d553728f67b57605bf1bb94e3802b4521b6304ee"
