/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux adam-virtual-machine 6.8.0-49-generic x86_64"
#define LGL_COMPILED "Mon Dec  9 20:18:03 CET 2024"
#define LGL_RELEASED "Mon Dec  9 20:18:03 CET 2024"
#define LGL_VERSION "1.0.0"
#define LGL_ID "d553728f67b57605bf1bb94e3802b4521b6304ee"
